/*
 * 直接模式
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2001
 */
public class InlineResponse2001Test {
    private final InlineResponse2001 model = new InlineResponse2001();

    /**
     * Model tests for InlineResponse2001
     */
    @Test
    public void testInlineResponse2001() {
        // TODO: test InlineResponse2001
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'msg'
     */
    @Test
    public void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'virifycodeid'
     */
    @Test
    public void virifycodeidTest() {
        // TODO: test virifycodeid
    }

    /**
     * Test the property 'virifyimage'
     */
    @Test
    public void virifyimageTest() {
        // TODO: test virifyimage
    }

    /**
     * Test the property 'confluxaddress'
     */
    @Test
    public void confluxaddressTest() {
        // TODO: test confluxaddress
    }

    /**
     * Test the property 'ethaddress'
     */
    @Test
    public void ethaddressTest() {
        // TODO: test ethaddress
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

}
