/*
 * 直接模式
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-01T20:54:45.948+08:00[Asia/Shanghai]")
public class InlineResponse2001 {
  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_MSG = "msg";
  @SerializedName(SERIALIZED_NAME_MSG)
  private String msg;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_VIRIFYCODEID = "virifycodeid";
  @SerializedName(SERIALIZED_NAME_VIRIFYCODEID)
  private String virifycodeid;

  public static final String SERIALIZED_NAME_VIRIFYIMAGE = "virifyimage";
  @SerializedName(SERIALIZED_NAME_VIRIFYIMAGE)
  private String virifyimage;

  public static final String SERIALIZED_NAME_CONFLUXADDRESS = "confluxaddress";
  @SerializedName(SERIALIZED_NAME_CONFLUXADDRESS)
  private String confluxaddress;

  public static final String SERIALIZED_NAME_ETHADDRESS = "ethaddress";
  @SerializedName(SERIALIZED_NAME_ETHADDRESS)
  private String ethaddress;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;


  public InlineResponse2001 state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * 响应状态分为：-1,0,1 分别代表响应错误、响应提示、响应成功
   * @return state
  **/
  @ApiModelProperty(required = true, value = "响应状态分为：-1,0,1 分别代表响应错误、响应提示、响应成功")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public InlineResponse2001 msg(String msg) {
    
    this.msg = msg;
    return this;
  }

   /**
   * 响应状态为-1时该值为错误信息。响应状态为0时，该值为响应提示信息。响应状态为1时该值为空字符串
   * @return msg
  **/
  @ApiModelProperty(required = true, value = "响应状态为-1时该值为错误信息。响应状态为0时，该值为响应提示信息。响应状态为1时该值为空字符串")

  public String getMsg() {
    return msg;
  }


  public void setMsg(String msg) {
    this.msg = msg;
  }


  public InlineResponse2001 phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public InlineResponse2001 virifycodeid(String virifycodeid) {
    
    this.virifycodeid = virifycodeid;
    return this;
  }

   /**
   * 验证码图片的ID值
   * @return virifycodeid
  **/
  @ApiModelProperty(required = true, value = "验证码图片的ID值")

  public String getVirifycodeid() {
    return virifycodeid;
  }


  public void setVirifycodeid(String virifycodeid) {
    this.virifycodeid = virifycodeid;
  }


  public InlineResponse2001 virifyimage(String virifyimage) {
    
    this.virifyimage = virifyimage;
    return this;
  }

   /**
   * data:image/png;base64
   * @return virifyimage
  **/
  @ApiModelProperty(required = true, value = "data:image/png;base64")

  public String getVirifyimage() {
    return virifyimage;
  }


  public void setVirifyimage(String virifyimage) {
    this.virifyimage = virifyimage;
  }


  public InlineResponse2001 confluxaddress(String confluxaddress) {
    
    this.confluxaddress = confluxaddress;
    return this;
  }

   /**
   * 树图区块链地址
   * @return confluxaddress
  **/
  @ApiModelProperty(required = true, value = "树图区块链地址")

  public String getConfluxaddress() {
    return confluxaddress;
  }


  public void setConfluxaddress(String confluxaddress) {
    this.confluxaddress = confluxaddress;
  }


  public InlineResponse2001 ethaddress(String ethaddress) {
    
    this.ethaddress = ethaddress;
    return this;
  }

   /**
   * 以太坊、Arbitrum、polygon、BSC等EVM链地址
   * @return ethaddress
  **/
  @ApiModelProperty(required = true, value = "以太坊、Arbitrum、polygon、BSC等EVM链地址")

  public String getEthaddress() {
    return ethaddress;
  }


  public void setEthaddress(String ethaddress) {
    this.ethaddress = ethaddress;
  }


  public InlineResponse2001 token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * 用户登录识别令牌，用于后续多个函数的交互，作为输入参数
   * @return token
  **/
  @ApiModelProperty(required = true, value = "用户登录识别令牌，用于后续多个函数的交互，作为输入参数")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.state, inlineResponse2001.state) &&
        Objects.equals(this.msg, inlineResponse2001.msg) &&
        Objects.equals(this.phone, inlineResponse2001.phone) &&
        Objects.equals(this.virifycodeid, inlineResponse2001.virifycodeid) &&
        Objects.equals(this.virifyimage, inlineResponse2001.virifyimage) &&
        Objects.equals(this.confluxaddress, inlineResponse2001.confluxaddress) &&
        Objects.equals(this.ethaddress, inlineResponse2001.ethaddress) &&
        Objects.equals(this.token, inlineResponse2001.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, msg, phone, virifycodeid, virifyimage, confluxaddress, ethaddress, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    virifycodeid: ").append(toIndentedString(virifycodeid)).append("\n");
    sb.append("    virifyimage: ").append(toIndentedString(virifyimage)).append("\n");
    sb.append("    confluxaddress: ").append(toIndentedString(confluxaddress)).append("\n");
    sb.append("    ethaddress: ").append(toIndentedString(ethaddress)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

