/*
 * 直接模式
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.InlineObject;
import org.openapitools.client.model.InlineObject1;
import org.openapitools.client.model.InlineObject2;
import org.openapitools.client.model.InlineResponse200;
import org.openapitools.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 检查手机号是否注册
     *
     * 检查手机号是否注册，返回“true”和“false”字符串
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void isPhoneRegPostTest() throws ApiException {
        InlineObject inlineObject = null;
        InlineResponse200 response = api.isPhoneRegPost(inlineObject);

        // TODO: test validations
    }
    
    /**
     * ①获取验证码图片
     *
     * 获取用于防御机器人的验证码图片，phone的传参必须为空字符串
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void juguguLoginCodeandReturnInfoPostTest() throws ApiException {
        InlineObject2 inlineObject2 = null;
        InlineResponse2001 response = api.juguguLoginCodeandReturnInfoPost(inlineObject2);

        // TODO: test validations
    }
    
    /**
     * ③注册Jugugu
     *
     * 注册jugugu，注意三点 1.phone的传参必须为11位的国内手机号。 2.robotcodeid和robotcode是通过【①】获得 3.code短信验证码通过【②】 4.paymentpassword区块链短密钥，该密钥为用户进行链上交互使用，密钥设置长度&gt;9位，且包含0-1 A-B a-b 已经特殊字符[~!@#$%^&amp;*?_+;&#39;,./\\|·！￥（）{}：“《》？、，。；’”\&quot;《》…-]+
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void jugugugRegAndVerifyandReturnInfoPostTest() throws ApiException {
        InlineObject1 inlineObject1 = null;
        InlineResponse2001 response = api.jugugugRegAndVerifyandReturnInfoPost(inlineObject1);

        // TODO: test validations
    }
    
}
